font:
  normal:
    family: DejaVuSansMono Nerd Font
  size: 10.0

import:
  - /home/scottclarke/.config/alacritty/dracula.yml

env:
  TERM: xterm-256color

key_bindings:
  - { key: Insert, mods: Shift, action: Paste }
