- hosts: localhost

  tasks:
  - name: Upgrade
    become: yes
    community.general.pacman:
      update_cache: True
      upgrade: True

  - name: Install packages
    become: yes
    community.general.pacman:
      name: "{{ item }}"
      state: present
    loop:
      - chromium
      - deepin-wayland
      - flatpak
      - git
      - neovim
      - rsync
      - tmux
      - yay
      - zsh

  - name: Install yay packages
    become: yes
    yay:
      name: "{{ item }}"
      state: present
    loop:
      - sway-git
      - waybar-git
