- hosts: localhost

  tasks:
  - name: Make config dir
    file:
      name: ./config
      state: directory

  - name: Copy config files
    synchronize:
      src: ~/.config/{{ item }}
      dest: ./config
    with_items:
      - alacritty
      - nvim
      - sway
      - waybar

  - name: Create home dir
    file:
      name: ./home
      state: directory

  - name: Copy home dir files
    synchronize:
      src: ~/{{ item }}
      dest: ./home
    with_items:
      - .gitconfig
      - .tmux.conf
      - .zshenv
      - .zshrc
      - .zprofile

  - name: Make Pictures dir
    file:
      name: ./Pictures
      state: directory

  - name: Copy background picture
    synchronize:
      src: ~/Pictures/Lighthouse.png
      dest: ./Pictures
