- hosts: localhost

  tasks:
  - name: Make config dir
    file:
      name: ./config
      state: directory
  - name: Copy config files
    synchronize:
      src: /home/scott/.config/{{ item }}
      dest: ./config
    with_items:
      - nvim
      - sway
      - waybar
      - i3
      - polybar
  - name: Create home dir
    file:
      name: ./home
      state: directory
  - name: Copy home dir files
    synchronize:
      src: /home/scott/{{ item }}
      dest: ./home
    with_items:
      - .fehbg
      - .gitconfig
      - .nvim/colors
      - .tmux.conf
      - .zshrc
      - .zprofile
  - name: Make Pictures dir
    file:
      name: ./Pictures
      state: directory
  - name: Copy background picture
    synchronize:
      src: /home/scott/Pictures/Lighthouse.png
      dest: ./Pictures
